### PR TITLE
docs: rename cloud features.

### PR DESCRIPTION
**Pull request by i4ki**

### CODE REVIEW

**Review by snakster — CHANGES_REQUESTED** [review]
You are still missing some occurrences, i.e. how-it-works.md. Best do a string search for the `--cloud` prefix.

**Comment by i4ki** [comment]
I forgot to commit all the files 😂 thanks!

**Review by snakster — CHANGES_REQUESTED** [review]
Still some cases of `--cloud-status=` unchanged.

**Review by snakster — APPROVED** [review]
👍

**Pull request merged**
