### PR TITLE
docs: update tag-filter.md to include --no-tags

### PR DESCRIPTION
**Pull request by luong-komorebi**

### CODE REVIEW

**Comment by i4ki** [comment]
Oh just saw this. Hey @AnnuCode please align here because you just did a similar PR.

**Comment by AnnuCode** [comment]
Hi @luong-komorebi , thanks for opening your first PR! I didn't know about this PR and opened a [similar one](https://github.com/terramate-io/terramate-docs/pull/94) at the same time (6 minutes difference). Can you please refer it to add a sidebar menu link for the Tag filter page? Then we can merge your PR 😃

**Comment by i4ki** [comment]
@luong-komorebi you are absolutely right, the `--no-tags` only support `,` separator! 

When you do:
```
--no-tags abc,xyz
```

is the same as doing:
```
--no-tags abc --no-tags xyz
```

**Comment by AnnuCode** [comment]
@luong-komorebi Thanks for the correction!

**Review by AnnuCode — APPROVED** [review]

**Review by i4ki — APPROVED** [review]
LGTM

Feel free to merge @luong-komorebi

**Pull request merged**
